name: Uberjar Containerize labeled

on:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  uberjar:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'build-docker-uberjar') || github.event.label.name == 'build-docker-uberjar' }}
    uses: ./.github/workflows/uberjar.yml
    secrets: inherit

  containerize:
    needs: [uberjar]
    if: ${{ contains(github.event.pull_request.labels.*.name, 'build-docker-uberjar') || github.event.label.name == 'build-docker-uberjar' }}
    uses: ./.github/workflows/containerize-uberjar.yml
    secrets: inherit
